CONCEPTS = [
    {
        "title": "Busqueda en juegos",
        "definition": "Proceso de analizar estados futuros posibles para decidir una accion en un juego.",
        "example": "En Tres en Raya, el agente examina donde podria poner X y como responderia O.",
        "question": "Que analiza un agente cuando realiza busqueda en juegos?",
        "options": ["Solo la jugada actual", "Estados futuros y respuestas del adversario", "El color del tablero", "Un resultado aleatorio"],
        "answer": "Estados futuros y respuestas del adversario",
        "feedback": "Correcto. La busqueda en juegos anticipa secuencias de acciones y respuestas.",
    },
    {
        "title": "Busqueda clasica vs adversarial",
        "definition": "La busqueda clasica busca una ruta a una meta; la adversarial considera un oponente que intenta impedirla.",
        "example": "Resolver un laberinto no tiene rival. En Tres en Raya, O puede bloquear las lineas de X.",
        "question": "Que hace diferente a la busqueda adversarial?",
        "options": ["No usa estados", "Incluye un adversario con objetivos opuestos", "Siempre es aleatoria", "No tiene utilidad"],
        "answer": "Incluye un adversario con objetivos opuestos",
        "feedback": "Correcto. La decision depende tambien de lo que el rival pueda hacer.",
    },
    {
        "title": "Arbol de juego",
        "definition": "Representacion de estados y jugadas posibles desde una posicion inicial.",
        "example": "La raiz es el tablero actual y cada rama es una casilla disponible para jugar.",
        "question": "Que representa una rama en el arbol de juego?",
        "options": ["Una accion posible", "El nombre del estudiante", "La puntuacion final siempre", "Un error del algoritmo"],
        "answer": "Una accion posible",
        "feedback": "Correcto. Cada rama conecta un estado con otro mediante una jugada.",
    },
    {
        "title": "Estado inicial",
        "definition": "Configuracion desde la cual empieza la busqueda o la partida.",
        "example": "Un tablero vacio de Tres en Raya es un estado inicial comun.",
        "question": "Cual puede ser el estado inicial en Tres en Raya?",
        "options": ["El tablero vacio", "Una carta oculta", "Un nodo podado", "La funcion de utilidad"],
        "answer": "El tablero vacio",
        "feedback": "Correcto. Desde ese tablero comienzan las acciones posibles.",
    },
    {
        "title": "Acciones",
        "definition": "Movimientos legales disponibles para un jugador en un estado.",
        "example": "Si hay cinco casillas vacias, existen cinco acciones posibles.",
        "question": "Que es una accion en Tres en Raya?",
        "options": ["Elegir una casilla vacia", "Cambiar las reglas", "Ocultar el tablero", "Finalizar siempre la partida"],
        "answer": "Elegir una casilla vacia",
        "feedback": "Correcto. Una accion transforma el tablero actual en un nuevo estado.",
    },
    {
        "title": "Estado terminal",
        "definition": "Estado donde la partida ya termino: victoria, derrota o empate.",
        "example": "Tres X en linea forman un estado terminal ganador para la IA.",
        "question": "Cuando aparece un estado terminal?",
        "options": ["Cuando el juego termina", "Cuando empieza el juego", "Cuando hay muchas ramas", "Cuando se registra el estudiante"],
        "answer": "Cuando el juego termina",
        "feedback": "Correcto. En ese punto se puede asignar utilidad al resultado.",
    },
    {
        "title": "Funcion de utilidad",
        "definition": "Regla que asigna valor numerico a resultados del juego.",
        "example": "X gana vale 1, empate vale 0 y O gana vale -1.",
        "question": "Para que sirve la funcion de utilidad?",
        "options": ["Para valorar resultados", "Para dibujar el tablero", "Para ocultar jugadas", "Para registrar correos"],
        "answer": "Para valorar resultados",
        "feedback": "Correcto. La utilidad permite comparar decisiones posibles.",
    },
    {
        "title": "Jugador MAX",
        "definition": "Agente que busca maximizar la utilidad esperada.",
        "example": "En este laboratorio, la IA con X es MAX.",
        "question": "En Minimax, que representa el jugador MAX?",
        "options": ["El jugador que busca perder", "El jugador que maximiza la utilidad", "El jugador aleatorio", "El jugador sin estrategia"],
        "answer": "El jugador que maximiza la utilidad",
        "feedback": "Correcto. MAX selecciona la accion con mayor utilidad esperada.",
    },
    {
        "title": "Jugador MIN",
        "definition": "Oponente que intenta minimizar la utilidad de MAX.",
        "example": "El estudiante con O puede bloquear o reducir las opciones ganadoras de X.",
        "question": "Que intenta hacer MIN?",
        "options": ["Maximizar a MAX", "Minimizar la utilidad de MAX", "No jugar", "Elegir siempre el centro"],
        "answer": "Minimizar la utilidad de MAX",
        "feedback": "Correcto. MIN representa un adversario racional.",
    },
    {
        "title": "Estrategia optima",
        "definition": "Plan de accion que logra el mejor resultado posible ante un rival que juega correctamente.",
        "example": "En Tres en Raya, una estrategia optima puede garantizar al menos empate.",
        "question": "Que supone una estrategia optima?",
        "options": ["Que el rival juega al azar", "Que ambos jugadores responden racionalmente", "Que no hay reglas", "Que solo importa la primera jugada"],
        "answer": "Que ambos jugadores responden racionalmente",
        "feedback": "Correcto. Minimax calcula decisiones bajo esa suposicion.",
    },
    {
        "title": "Complejidad computacional",
        "definition": "Costo de tiempo o memoria requerido para explorar estados.",
        "example": "Un tablero grande genera muchos mas nodos que Tres en Raya.",
        "question": "Que ocurre cuando aumenta el arbol de juego?",
        "options": ["Puede crecer el costo computacional", "Desaparecen las acciones", "La utilidad no existe", "Siempre se gana"],
        "answer": "Puede crecer el costo computacional",
        "feedback": "Correcto. Por eso se usan podas, limites y heuristicas.",
    },
    {
        "title": "Heuristica",
        "definition": "Estimacion practica para valorar estados cuando no se puede explorar todo.",
        "example": "Preferir centro y esquinas puede ser una heuristica simple en Tres en Raya.",
        "question": "Cuando son utiles las heuristicas?",
        "options": ["Cuando no se puede explorar todo el arbol", "Solo cuando no hay adversario", "Para borrar estados", "Para ocultar informacion visible"],
        "answer": "Cuando no se puede explorar todo el arbol",
        "feedback": "Correcto. Ayudan a decidir bajo recursos limitados.",
    },
]


QUIZ_QUESTIONS = [
    {
        "question": "Que caracteriza la busqueda en juegos?",
        "options": ["Explora acciones y respuestas futuras", "Solo ordena datos", "Ignora al adversario", "No usa estados"],
        "answer": "Explora acciones y respuestas futuras",
        "feedback": "La busqueda en juegos simula posibles secuencias de decisiones.",
    },
    {
        "question": "En Minimax, quien es MAX?",
        "options": ["El agente que maximiza utilidad", "El jugador que minimiza utilidad", "Un jugador aleatorio", "El tablero"],
        "answer": "El agente que maximiza utilidad",
        "feedback": "MAX busca el resultado con mayor utilidad.",
    },
    {
        "question": "Que representa MIN?",
        "options": ["El adversario que reduce la utilidad de MAX", "Una funcion matematica sin jugador", "La primera jugada", "La poda alfa"],
        "answer": "El adversario que reduce la utilidad de MAX",
        "feedback": "MIN modela a un rival racional con intereses opuestos.",
    },
    {
        "question": "Que hace una funcion de utilidad?",
        "options": ["Asigna valor a resultados o estados", "Dibuja botones", "Registra archivos", "Elimina la necesidad de reglas"],
        "answer": "Asigna valor a resultados o estados",
        "feedback": "La utilidad convierte resultados en valores comparables.",
    },
    {
        "question": "Que calcula Minimax?",
        "options": ["La mejor jugada suponiendo respuestas optimas", "Un movimiento siempre aleatorio", "Solo el numero de jugadores", "La velocidad del computador"],
        "answer": "La mejor jugada suponiendo respuestas optimas",
        "feedback": "Minimax alterna decisiones de MAX y MIN.",
    },
    {
        "question": "Que ventaja tiene la poda Alfa-Beta?",
        "options": ["Reduce nodos sin cambiar la decision optima", "Cambia las reglas", "Hace visible informacion oculta", "Elimina la utilidad"],
        "answer": "Reduce nodos sin cambiar la decision optima",
        "feedback": "Alfa-Beta descarta ramas que no pueden mejorar la decision.",
    },
    {
        "question": "Cual es un juego de informacion perfecta?",
        "options": ["Tres en Raya", "Poker", "Batalla naval con barcos ocultos", "Cartas con mano oculta"],
        "answer": "Tres en Raya",
        "feedback": "En Tres en Raya ambos jugadores observan todo el tablero.",
    },
    {
        "question": "Que define a la informacion imperfecta?",
        "options": ["Hay datos relevantes ocultos o inciertos", "Todos ven todo", "No existen turnos", "Siempre hay empate"],
        "answer": "Hay datos relevantes ocultos o inciertos",
        "feedback": "Poker es un ejemplo clasico por las cartas privadas.",
    },
    {
        "question": "Por que los juegos en tiempo real suelen usar profundidad limitada?",
        "options": ["Porque hay poco tiempo para decidir", "Porque no tienen estados", "Porque no hay adversarios", "Porque siempre son simples"],
        "answer": "Porque hay poco tiempo para decidir",
        "feedback": "La restriccion temporal impide explorar todo el arbol.",
    },
    {
        "question": "Que es una heuristica?",
        "options": ["Una estimacion para decidir con informacion parcial o tiempo limitado", "Una victoria garantizada", "Una rama podada", "Una casilla del tablero"],
        "answer": "Una estimacion para decidir con informacion parcial o tiempo limitado",
        "feedback": "Las heuristicas aproximan la calidad de un estado.",
    },
]
